### ISSUE TITLE
No sdist on PyPI for 1.5.19: the swig 4.5 fix does not reach GNU/Linux users

### ISSUE THREAD

**Issue by kairi4** [LudovicRousseau/PyKCS11#169]
**Describe the bug**

Follow-up to #167.

1.5.19 on PyPI has 19 wheels and no sdist.
PyKCS11 does not publish Linux wheels, so on GNU/Linux the sdist is the only distribution available from PyPI.
`pip install pykcs11` therefore falls back to 1.5.18, which still fails to build with swig 4.5.0.
From a Linux user's point of view, the fix from #167 has been released but nothing has changed.

| version | files | sdist |
|---------|-------|-------|
| 1.5.17  | 14    | 1     |
| 1.5.18  | 16    | 1     |
| 1.5.19  | 19    | 0     |

The source is on SourceForge as `pykcs11-1.5.19.tar.gz` (with its `.asc`), and the Debian sid package is built from it.
I installed that tarball on Linux with swig 4.5.0 and it compiled and imported fine, so uploading that same file to PyPI should be all that is needed.

**To Reproduce**

```
$ docker run --rm --platform linux/amd64 python:3.12 pip install pykcs11
Collecting pykcs11
  Downloading pykcs11-1.5.18.tar.gz (105 kB)
  ...
      src/pykcs11_wrap.cpp:15342:17: error: 'PyInt_FromLong' was not declared in this scope; did you mean 'PyLong_FromLong'?
ERROR: Failed to build installable wheels for some pyproject.toml based projects (pykcs11)
```

```
$ curl -s https://pypi.org/pypi/pykcs11/1.5.19/json | jq '[.urls[].packagetype] | unique'
["bdist_wheel"]
```

For 1.5.18 the same command returns `["bdist_wheel", "sdist"]`.

**Expected behavior**

1.5.19 on PyPI includes an sdist, so that `pip install pykcs11` builds 1.5.19 from source on GNU/Linux.

**Your system information:**

 - Operating system used: Debian (`python:3.12` container, linux/amd64)
 - PyKCS11 version: 1.5.19 and 1.5.18
 - Python version: 3.12.14
 - PKCS#11 library used: N/A (this is a packaging issue)

**Additional context**

One caveat: PyPI seems to refuse new files on a release more than 14 days old (`MAXIMUM_AGE_FOR_NEW_UPLOADS_DAYS = 14` in warehouse), so for 1.5.19 that window closes around 9 September.
If it is easier to leave it for the next release, that works too.

The build jobs do produce an sdist, but `upload-artifact` only picks up `dist/*.whl`, so it never reaches the publish step.
I am happy to send a PR for that if it would be useful.

And if leaving the sdist out was intentional, that is good to know as well; I will adjust things on our side.

**Comment by LudovicRousseau** [comment]
It was a mistake from me sorry.

I will manually upload the source code to PyPI.
I do not trust github/Microsoft enough to upload the source code with a github action.

**Comment by LudovicRousseau** [comment]
Source code uploaded.
Thanks for the bug report.
