### PR TITLE
Appveyor configuration

### PR DESCRIPTION
**Pull request by denisenkom**
This change introduces configuration for Appveyor which allows testing on Windows platform.

### CODE REVIEW

**Comment by LudovicRousseau** [comment]
Your changes breaks the build on GNU/Linux. I will fix that.

I configured AppVeyor for https://ci.appveyor.com/project/LudovicRousseau/pykcs11-debug but I can't find the build results. They used to be in ARTIFACTS but I find nothing here. Where are they?

**Comment by denisenkom** [comment]
I have not configured artifacts yet.  Currently it only does building and testing.

**Comment by LudovicRousseau** [comment]
I included most of your changes in my test project https://github.com/LudovicRousseau/PyKCS11-debug

All works https://ci.appveyor.com/project/LudovicRousseau/pykcs11-debug except the build on Windows for Python 2.7. The error is:
```
src/pykcs11_wrap.cpp(15491) : error C2039: 'data' : is not a member of 'std::vector<_Ty>'
        with
        [
            _Ty=unsigned char
        ]
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 9.0\\VC\\BIN\\cl.exe' failed with exit status 2
```

I see you changed src/pykcs11.i in https://github.com/LudovicRousseau/PyKCS11/pull/29/files#diff-65d3a6436b9f69065c5876342612e395L236
After searching a bit it looks like ``data()`` for vectors has been introduced in C++11 and should be preferred to ``operator[](0)``. See https://stackoverflow.com/a/10740266

Is it possible to make Microsoft Visual Studio 9.0 use C++11?
Why does the build works for Python 3.6 and all Python for Windows 64-bits? The compiler used is different?

**Comment by denisenkom** [comment]
> Is it possible to make Microsoft Visual Studio 9.0 use C++11?
I don't know, it may be possible, I will look into that.

> Why does the build works for Python 3.6 and all Python for Windows 64-bits? The compiler used is different?
Yes, newer versions of Python use different compiler, see: https://wiki.python.org/moin/WindowsCompilers#Which_Microsoft_Visual_C.2B-.2B-_compiler_to_use_with_a_specific_Python_version_.3F

**Comment by denisenkom** [comment]
Looks like VS 9.0 (2008) does not support C++11 features: https://stackoverflow.com/questions/20302891/visual-studio-2008-with-c11.

**Comment by LudovicRousseau** [comment]
Can we drop support of Python 2.7?
I also see that you build for both Python 3.5 and 3.6 for 64-bits. Is 3.5 really useful?

**Comment by denisenkom** [comment]
I believe Python 2.7 is still very popular, on par with 3.x, I would argue against dropping support for it.

Python 3.5 is probably used a lot, since 3.6 is relatively new, and testing on different versions of Python is relatively cheap so why not.

**Comment by LudovicRousseau** [comment]
I merged your changes.
Please continue your work with AppVeyor to provide artifacts.

**Comment by denisenkom** [comment]
Thank you, will do
